//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunsetHotelSystem.Dominio.Entidades
{
    using Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Sunset_HotelDBEntities : DbContext
    {
        public Sunset_HotelDBEntities()
            : base("name=Sunset_HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TSH_Caracteristica_habitacion> TSH_Caracteristica_habitacion { get; set; }
        public virtual DbSet<TSH_Cliente> TSH_Cliente { get; set; }
        public virtual DbSet<TSH_Habitacion> TSH_Habitacion { get; set; }
        public virtual DbSet<TSH_Pag_Facilidades> TSH_Pag_Facilidades { get; set; }
        public virtual DbSet<TSH_Pag_Home> TSH_Pag_Home { get; set; }
        public virtual DbSet<TSH_Pagina> TSH_Pagina { get; set; }
        public virtual DbSet<TSH_Publicidad> TSH_Publicidad { get; set; }
        public virtual DbSet<TSH_Reserva> TSH_Reserva { get; set; }
        public virtual DbSet<TSH_SobreN_Galeria> TSH_SobreN_Galeria { get; set; }
        public virtual DbSet<TSH_Tipo_Habitacion> TSH_Tipo_Habitacion { get; set; }
    }
}
